version: '3.0'
services:
  app:
    build: .
    ports: ['8081:8080']
    environment:
      - SPRING_DATA_ELASTICSEARCH_CLUSTER-NODES=elasticsearch:9300
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    ports: ['9200:9200','9300:9300']
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
    volumes:
      - 'elasticsearch-data:/usr/share/elasticsearch/data'

volumes:
  elasticsearch-data: